# Generated by cucumber-sinatra. (2013-11-04 14:26:04 +0000)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/takeaway.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = Takeaway

class TakeawayWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  TakeawayWorld.new
end
